service: s3-now

package:
  exclude:
    - node_modules/**
    - .idea/**
    - .venv/**
    - package.json
    - requirements.txt
    - README.md

provider:
  name: aws
  runtime: python3.7
  region: eu-west-1
  stage: ${opt:stage, 'dev'}

  environment: ${file(env.yml):${self:provider.stage}, file(env.yml):default}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*"

functions:
  json:
    handler: storage.json_request
    events:
      - http:
          path: json
          method: get
      - http:
          path: json
          method: post

resources:
  Resources:
    S3BucketPhotos:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}

